# Generated by Django 3.0.2 on 2020-06-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_code', models.CharField(max_length=30)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('hours_worked', models.IntegerField()),
                ('over_time', models.IntegerField()),
            ],
        ),
    ]
