# Generated by Django 3.0.2 on 2020-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='over_time',
            field=models.CharField(max_length=2),
        ),
    ]
