# Generated by Django 3.0.2 on 2020-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_manager', '0002_auto_20200624_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='over_time',
            field=models.IntegerField(),
        ),
    ]
